{% set name = "poetry-plugin-export" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-plugin-export-{{ version }}.tar.gz
  sha256: e7796292eaafac1316149f3a8070923c2a2214c98d046de1246b4d8eb0b0c84b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry >=1.2.0b1dev0,<2.0.0
  run:
    - poetry >=1.2.0b1dev0,<2.0.0
    - python >=3.7,<4.0

test:
  imports:
    - poetry_plugin_export
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-plugin-export/
  summary: Poetry plugin to export the dependencies to various formats
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - maresb
